# https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml
version: '3'

services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    # https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker
    ports:
      - 127.0.0.1:22300:22300
    restart: unless-stopped
    environment:
      - APP_BASE_URL= # full url, ending with ${SUBPATH} if using subpath
      - APP_PORT=22300

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80 # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy-config:/config
      - ./data/caddy-data:/data
      - ./logrotate/caddy:/etc/logrotate.d/caddy:ro
    environment:
      - DOMAIN= # domain must not end with '/'
      - EMAIL= # The email address to use for ACME registration
      - SUBPATH=${SUBPATH}
      - LOG_FILE=/data/caddy.log